### PR TITLE
Add platforms

### PR DESCRIPTION
**Pull request by mikaem**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by dalcinl** [comment]
Maybe it would be better to just fix the `mpi4py-fft` sources to support Cython 3 and make a new release?

**Comment by mikaem** [comment]
> 

Mayhaps. We need to upgrade to latest cython sooner or later anyway. Not sure it will fix this arm- problem though, didn't understand much of the error message.

**Comment by dalcinl** [comment]
@conda-forge-admin, please rerender

**Comment by dalcinl** [comment]
@mikaem As you are adding a new platform that needs cross-compiling, the recipe has to be updated. See the [petsc](https://github.com/conda-forge/petsc4py-feedstock/blob/main/recipe/meta.yaml#L35) recipe as an example. If you are really in a hurry, take the lead and experiment. Otherwise I can handle it later, I cannot work on it right now.

**Comment by mikaem** [comment]
@dalcinl  I know too little about cross-compiling and is not in a hurry, so later sounds great:-)

**Comment by dalcinl** [comment]
@mikaem I believe we are good to go. Take a final look, if everything is OK with you, please click the merge button.

**Review by dalcinl — APPROVED** [review]

**Comment by mikaem** [comment]
Great😃 So this fixes the cross-compilation, but cython is still < 3, right? @dalcinl

**Comment by dalcinl** [comment]
> but cython is still < 3

The Cython version number jumped from 0.29.36 to 3.0.0, to align the major version number 3 with Python.

**Comment by dalcinl** [comment]
I believe I misunderstood your question. Work on upgrading to Cython 3 is underway in mpi4py/mpi4py-fft#29.

**Pull request merged**
